accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),

    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),

    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),


]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [

    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')

]

trendapp/urls.py
from django.urls import path

from trendapp.views import BasicTemplateView, TrendListView, let_write

app_name = 'trendapp'

urlpatterns = [
    path('info/', BasicTemplateView.as_view(), name='info'),
    path('list/', TrendListView.as_view(), name='list'),
    path('let_write/', let_write, name='let_write'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">

{% include 'header.html' %}

<hr>

{% for message in messages %}
    <div class="text-center my-4">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align: center">
    <div class="pragmatic_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스소개</span>
    </div>
    <div class="pragmatic_footer_logo">
        <h5>광주 소비자 물가 알림e 서비스</h5>
    </div>

</div>

templates/head.html
{% load static %}

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=devise-width, initial-scale=1, shrink-to-fit=no">
    <title>광주물가알림e</title>

    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# GOOGLE FONTS LINK #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">


    {# DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">
    <div class="pragmatic_header_logo">
        <a href="{% url 'home' %}">
            <h1>광주광역시</h1>
            <h2>소비자 물가 동향 알림e</h2>
        </a>
    </div>
    <div class="pragmatic_header_button">
        <span class="mx-2">
            <a href="{% url 'articleapp:list' %}">
                전체 구역
            </a>
        </span>
        <span class="mx-2">
            <a href="{%  url 'trendapp:info' %}">
                물가 동향
            </a>
        </span>

        {% if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accountapp:login' %}">
                로그인
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:create' %}">
                가입하기
            </a>
        </span>
        {% else %}
        <span class="mx-2">
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                내 페이지
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:logout' %}">
                로그아웃
            </a>
        </span>
        {% endif %}
    </div>
</div>